spring:
  datasource:
     url: jdbc:mysql://localhost:3306/mysql?characterEncoding=UTF-8                #数据库地址，url: jdbc:mysql://localhost:3306/mysql
     userName: root                                           #<!--用户名-->
     password: 1024
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     show-sql: true
     properties:
      hibernate:
       format_sql: true                                      #//数据库查询语句不换行，格式清晰
server:
  port: 8082

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
logging:
  level:
    com.som.springboot.mapper: debug
#mybatis:
#  mapper-locations: classpath:mappers/Person.xml
